FROM node:20-alpine

WORKDIR /app

# Copie package.json e lock para instalar dependências
COPY package*.json ./

# Copie a pasta do Prisma ANTES do npm install
COPY prisma ./prisma

# Agora rode o npm install (prisma generate funcionará)
RUN npm install

# Copie o resto do código
COPY . .

EXPOSE 3000
EXPOSE 5555

CMD ["npm", "run", "dev"]